### ISSUE TITLE
Problem in algo implementation

### ISSUE THREAD

**Issue by mayankpathak19** [gustavosm/uri#1]
I tried implementing your code in python, and encountered WA 90%, here is the link [code](https://www.urionlinejudge.com.br/judge/en/runs/code/7913280), are you sure this implementation works
I even tried it in c++ and yet the answer was WA 90%, here is the link [code](https://www.urionlinejudge.com.br/judge/en/runs/code/7913489)

**Comment by gustavosm** [comment]
It's possible that I have uploaded an incorret file, I'm sorry...

I can't see your code in URI... 
Can you paste it on pastebin and say which problem you are talking about?
Thanks

**Comment by mayankpathak19** [comment]
1682 - Genetic Code
[Python](https://ideone.com/R8of8W)
[C++](https://ideone.com/yuCZFD)

**Comment by gustavosm** [comment]
You're right, I had uploaded an incorrect file...
It's fine now, you may check it...
Thanks!
